### ISSUE TITLE
Update prilikom iscrtavanja

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG119-pacman#1]
Update svih kretanja se trenutno vrsi u on_display funkciji. Ovo moze uzrokovati dosta bagova vezanih za brzinu animacije na razlicitim racunarima. Bolje je odvojiti kod za update-ovanje i staviti ga u funkciju koja vrsi pomeranje sveta npr on_timer. A u on_display-u i slicnim funkcijama raditi samo to sto kazu - iscrtavati ekran.

**Comment by wnsmith** [comment]
Update kretanja je sada izdvojen u posebnu funkciju, koja se poziva u on_timer.
@rastko-djordjevic-edu
